
version: 2

models:
    - name: mart_weather_trend_analysis
      description: " "
      columns:
          - name: wind_speed
            description: "The primary key for this table"
            tests:
                
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
